module.exports = [
  'Oskar & Chili Sammlung',
  'Dogs Sammlung',
  'Bikes Sammlung',
  'Cats Sammlung',
  'Streetart Sammlung',
  'Ausflüge Sammlung',
  'Memes Sammlung',
  'Sewing, DIY & Upcycling Sammlung',
  'Tickets Sammlung',
  'Paintings Sammlung',
  'Shoes Sammlung',
  'Me Waving Sammlung',
  'Owls Sammlung',
  'Gardening Tools Sammlung',
  'Clas Ohlson Sammlung',
  'I See Faces Sammlung',
  'Streetlights Sammlung',
  'Records Sammlung',
  'Mixed Pickles Sammlung',
  'Color Key Sammlung',
  'Me and my friends Sammlung',
  '2013-08-25 Fisheye',
  'Live Music Sammlung',
  'Demos Sammlung',
  'My Artworks Sammlung',
  'Screenshots Sammlung',
  'Crotches Sammlung',
  '2013 Pictures I love',
  '2009-01-27 Calexico live @Roxy Ulm',
];
